services:
  db_service_dev:
    image: postgres:17-alpine
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data
    restart: on-failure
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=basedb
    ports:
      - "1032:5432"

volumes:
  data:
